version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "3000:3000"
        - "8000:8000"
        - "8080:8080"
      environment: 
        - DATABASE_URL=postgresql://postgres:myscretpassword@postgres:5432/postgres
      depends on:
        - postgres
      
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: